### ISSUE TITLE
SaveRunning Does not work on ASA

### ISSUE THREAD

**Issue by mzarglis** [PresidioCode/SecureCRT#28]
AttributeError

Error: 'NoneType' object has no attribute 'group'
line: 69
session = StartSession(crt)

**Comment by jamiecaesar** [comment]
I haven't tested against ASAs much.  There are a couple issues with these scripts working against the ASAs.   I think I have them fixed, but I'm going to put the code in the "dev" branch so I can do some more testing with it.  Feel free to run that version of the scripts and if things seem stable, I'll merge it into the master branch.

**Comment by mzarglis** [comment]
Tested the rewrite branch on:

asa 8.29(x) & 9.1(x) code lines successfully

**Comment by jamiecaesar** [comment]
Thanks for reporting back on how the updates have worked.  I haven't been doing much firewall work lately, so that is a weak area for the scripts (plus the CLI is different enough to cause problems).

Also, thanks for pointing out that comment from the json file --  I do need to add that that info to both places (I don't think I ever got around to enabling debug mode, so that is a pointless setting for now...  Ultimately I'd like it to create logs for each run when enabled for easier troubleshooting but finding the time is always an issue)

I'll close the issue since this sounds resolved.
