### ISSUE TITLE
Help with Ubuntu and SecureCRT8.5

### ISSUE THREAD

**Issue by aegcni81** [PresidioCode/SecureCRT#42]
Hello.

I'm new using scripts with SecureCRT, so I want to run the script "Document_Device.py", but it's getting me the following **Error: Type must be a string** at **line 62**. I have already copy and rename the script "script_settings_default.py" to "script_settings.py" and change line 29 with the following: settings['savepath'] = '/home/newuser/Documents/SecureCRT-master', all the other required scripts are in that folder.

Thanks in advanced for any help.

Best Regards.

**Comment by jamiecaesar** [comment]
Based on the script name and the settings .py file, you are running a pretty old version of the scripts which I probably can't even troubleshoot effectively at this point since they have changed so much.   I'd recommend pulling down the latest version of the repository first and then letting me know if you run into any problems.   For example, there is now a setting.ini file that is automatically created the first time you run any of the scripts (you'll have to update it manually -- no conversion happens from the .py file) and there is much more documentation for this version of them.  

There is a "s_document_device.py" script in the newer repo that is the newer version of that script, but pulls its list of commands from the setting.ini file, which you can edit to customize the list.  Please follow up if you have any problems with the newer versions and then I'll be able to debug the code much better, if needed.

**Comment by aegcni81** [comment]
Thank you very much.
